#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -i|--init)
    PWD = $(pwd)
    echo $PWD
    docker run --name=e2e-docker -d -t e2e
    shift # past argument
    ;;
    -e|--end)
    docker kill e2e-docker
    docker rm e2e-docker
    shift # past argument
    ;;
    -r|--run)
    docker cp $PWD/$2 e2e-docker:/opt/e2e/project
    docker exec -i -t e2e-docker /opt/e2e/project/run-end.sh $2
    docker cp e2e-docker:/opt/e2e/project/$2.output $PWD
    shift # past argument
    shift # past value
    ;;
    -h|--help)
        echo "Usage: ./end2end [option]"
        echo " "
        echo "Options:"
        echo "-i, --init        Initialize e2e tool."
        echo "-r, --run file    Run the e2e tool on file"
        echo "-e, --end         Terminate e2e tool"
        echo "-k                The number of consecutive windows. Default value is 3"
        shift
        ;;
    *)    # unknown option
    echo "Unknown option"
    echo "See e2e --help"
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

