/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 216 "/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 133 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __pid_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 147 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __clockid_t;
#line 150 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef void *__timer_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 150 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 98 "/usr/include/x86_64-linux-gnu/sys/types.h"
typedef __pid_t pid_t;
#line 91 "/usr/include/time.h"
typedef __clockid_t clockid_t;
#line 103 "/usr/include/time.h"
typedef __timer_t timer_t;
#line 27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
struct __anonstruct___sigset_t_15 {
   unsigned long __val[1024UL / (8UL * sizeof(unsigned long ))] ;
};
#line 27 "/usr/include/x86_64-linux-gnu/bits/sigset.h"
typedef struct __anonstruct___sigset_t_15 __sigset_t;
#line 37 "/usr/include/x86_64-linux-gnu/sys/select.h"
typedef __sigset_t sigset_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 60 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef unsigned long pthread_t;
#line 63 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union pthread_attr_t {
   char __size[56] ;
   long __align ;
};
#line 69 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union pthread_attr_t pthread_attr_t;
#line 75 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __pthread_internal_list {
   struct __pthread_internal_list *__prev ;
   struct __pthread_internal_list *__next ;
};
#line 75 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef struct __pthread_internal_list __pthread_list_t;
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __pthread_mutex_s {
   int __lock ;
   unsigned int __count ;
   int __owner ;
   unsigned int __nusers ;
   int __kind ;
   short __spins ;
   short __elision ;
   __pthread_list_t __list ;
};
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union __anonunion_pthread_mutex_t_17 {
   struct __pthread_mutex_s __data ;
   char __size[40] ;
   long __align ;
};
#line 90 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union __anonunion_pthread_mutex_t_17 pthread_mutex_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
struct __anonstruct___data_20 {
   int __lock ;
   unsigned int __futex ;
   unsigned long long __total_seq ;
   unsigned long long __wakeup_seq ;
   unsigned long long __woken_seq ;
   void *__mutex ;
   unsigned int __nwaiters ;
   unsigned int __broadcast_seq ;
};
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
union __anonunion_pthread_cond_t_19 {
   struct __anonstruct___data_20 __data ;
   char __size[48] ;
   long long __align ;
};
#line 139 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h"
typedef union __anonunion_pthread_cond_t_19 pthread_cond_t;
#line 31 "/usr/include/x86_64-linux-gnu/bits/setjmp.h"
typedef long __jmp_buf[8];
#line 34 "/usr/include/setjmp.h"
struct __jmp_buf_tag {
   __jmp_buf __jmpbuf ;
   int __mask_was_saved ;
   __sigset_t __saved_mask ;
};
#line 48 "/usr/include/setjmp.h"
typedef struct __jmp_buf_tag jmp_buf[1];
#line 92 "/usr/include/setjmp.h"
typedef struct __jmp_buf_tag sigjmp_buf[1];
#line 742 "/usr/include/pthread.h"
struct __jmp_buf_tag;
#line 25 "/usr/include/asm-generic/int-ll64.h"
typedef int __s32;
#line 26 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned int __u32;
#line 30 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned long long __u64;
#line 48 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct threadqueue {
   pthread_mutex_t mutex ;
   pthread_cond_t cond ;
};
#line 97 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct tp_struct {
   int waiting ;
   jmp_buf env ;
   timer_t *tmr ;
};
#line 117 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cbm {
   int use ;
   int data ;
   struct cbm *nextc ;
};
#line 117 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
typedef struct cbm cbm;
#line 123 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cab_ds {
   struct cbm *free ;
   struct cbm *mrb ;
   int maxcbm ;
};
#line 133 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct fifolist {
   int data ;
   struct timespec ts ;
   struct fifolist *nextf ;
   pthread_mutex_t mutx ;
};
#line 140 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct sched_attr {
   __u32 size ;
   __u32 sched_policy ;
   __u64 sched_flags ;
   __s32 sched_nice ;
   __u32 __sched_priority ;
   __u64 sched_runtime ;
   __u64 sched_deadline ;
   __u64 sched_period ;
};
#line 104 "/usr/include/getopt.h"
struct option {
   char const   *name ;
   int has_arg ;
   int *flag ;
   int val ;
};
#line 272 "/usr/include/stdio.h"
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 764 "/usr/include/stdlib.h"
extern void ( __attribute__((__nonnull__(1,4))) qsort)(void *__base , size_t __nmemb , size_t __size , int (*__compar)(void const   * , void const   * ) ) ;
#line 759 "/usr/include/unistd.h"
extern  __attribute__((__nothrow__)) __pid_t fork(void) ;
#line 1061
extern  __attribute__((__nothrow__)) long ( __attribute__((__leaf__)) syscall)(long __sysno  , ...) ;
#line 342 "/usr/include/time.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) clock_gettime)(clockid_t __clock_id , struct timespec *__tp ) ;
#line 59 "/usr/include/setjmp.h"
extern  __attribute__((__nothrow__)) int __sigsetjmp(struct __jmp_buf_tag *__env , int __savemask ) ;
#line 233 "/usr/include/pthread.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,3))) pthread_create)(pthread_t * __restrict  __newthread , pthread_attr_t const   * __restrict  __attr , void *(*__start_routine)(void * ) , void * __restrict  __arg ) ;
#line 250
extern int pthread_join(pthread_t __th , void **__thread_return ) ;
#line 22 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int policy  =    0;
#line 88 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct timespec *timepecptr  ;
#line 89 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
timer_t ftimer  ;
#line 90 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
sigset_t sigtype  ;
#line 91
extern int ktc_critical_end(sigset_t *orig_mask ) ;
#line 92
extern int ktc_critical_start(sigset_t *orig_mask ) ;
#line 93
extern int ktc_set_sched(int policy , int runtime , int deadline , int period ) ;
#line 104 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
_Bool boolvar  ;
#line 105 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct tp_struct tp_struct_data  ;
#line 106 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int list_pr[500]  = {      4};
#line 107 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
int list_dl[500]  = {      4};
#line 108
extern void ktc_create_timer(timer_t *ktctimer , struct tp_struct *tp , int num ) ;
#line 109
extern int ktc_start_time_init(struct timespec *start_time ) ;
#line 110
extern long ktc_sdelay_init(int deadline , int period , int unit , struct timespec *start_time , int id ) ;
#line 111
extern long ktc_gettime(int unit ) ;
#line 112
extern long ktc_fdelay_init(int interval , int period , int unit , struct timespec *start_time , int id , int num , int retjmp ) ;
#line 113
extern long ktc_block_signal(int n ) ;
#line 114 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
sigjmp_buf buf_struct  ;
#line 130 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
cbm cabmsgv  ;
#line 131 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct cab_ds cabdsv  ;
#line 158 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct sched_attr sae  ;
#line 159 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct fifolist fifoex  ;
#line 161
extern int compare_qsort(void const   *elem1 , void const   *elem2 ) ;
#line 162
int populatelist(int num ) ;
#line 163
extern struct cbm *ktc_htc_reserve(struct cab_ds *cab ) ;
#line 164
extern void ktc_htc_putmes(struct cab_ds *cab , struct cbm *buffer ) ;
#line 165
extern cbm *ktc_htc_getmes(struct cab_ds *cab ) ;
#line 166
extern void ktc_htc_unget(struct cab_ds *cab , cbm *buffer ) ;
#line 167
extern int ktc_fifo_init(struct threadqueue *queue ) ;
#line 168
extern void ktc_fifo_write(struct threadqueue *queue , void *fifolistt , int *fifocount , int *fifotail , void *data , int size ) ;
#line 169
extern void ktc_fifo_read(struct threadqueue *queue , void *fifolistt , int *fifocount , int *fifotail , void *data , int size , struct timespec *wt ) ;
#line 170
extern void ktc_simpson(int *sdata , int *tdata ) ;
#line 172 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
size_t s  ;
#line 173 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
struct option o  ;
#line 174 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
__inline static int sched_getattr(pid_t pid , struct sched_attr *attr , unsigned int size , unsigned int flags ) 
{ 
  int tmp ;

  {
#line 174
  tmp = (int )syscall(315, pid, attr, size, flags);
#line 174
  return (tmp);
}
}
#line 233
extern int ktc_fdelay_start_timer(int interval , int unit , timer_t ktctimer , struct timespec *start_time ) ;
#line 234 "/home/saranya/Dokument/ktc/bin/../include/cilktc.h"
pthread_t pthread_id_example  ;
#line 261
/* #pragma cilnoremove("compare_qsort") */
#line 262
/* #pragma cilnoremove("ktc_htc_reserve") */
#line 263
/* #pragma cilnoremove("ktc_htc_putmes") */
#line 264
/* #pragma cilnoremove("ktc_htc_getmes") */
#line 265
/* #pragma cilnoremove("ktc_htc_unget") */
#line 266
/* #pragma cilnoremove("cabmsgv") */
#line 267
/* #pragma cilnoremove("cabdsv") */
#line 268
/* #pragma cilnoremove("boolvar") */
#line 269
/* #pragma cilnoremove("fork") */
#line 270
/* #pragma cilnoremove("exec_child") */
#line 271
/* #pragma cilnoremove("pthread_id_example") */
#line 272
/* #pragma cilnoremove("sigtype") */
#line 273
/* #pragma cilnoremove("next") */
#line 274
/* #pragma cilnoremove("ktc_start_time_init") */
#line 275
/* #pragma cilnoremove("ktc_sdelay_init") */
#line 276
/* #pragma cilnoremove("ktc_fdelay_init") */
#line 277
/* #pragma cilnoremove("ktc_block_signal") */
#line 278
/* #pragma cilnoremove("timepecptr") */
#line 279
/* #pragma cilnoremove("env") */
#line 280
/* #pragma cilnoremove("ftimer") */
#line 281
/* #pragma cilnoremove("ktc_create_timer") */
#line 282
/* #pragma cilnoremove("tp_struct_data") */
#line 283
/* #pragma cilnoremove("__sigsetjmp") */
#line 284
/* #pragma cilnoremove("pthread_join") */
#line 285
/* #pragma cilnoremove("pthread_tryjoin_np") */
#line 286
/* #pragma cilnoremove("pthread_create") */
#line 287
/* #pragma cilnoremove("ktc_fdelay_start_timer") */
#line 288
/* #pragma cilnoremove("ktc_critical_end") */
#line 289
/* #pragma cilnoremove("ktc_critical_start") */
#line 290
/* #pragma cilnoremove("fifoex") */
#line 291
/* #pragma cilnoremove("ktc_fifo_init") */
#line 292
/* #pragma cilnoremove("ktc_fifo_read") */
#line 293
/* #pragma cilnoremove("ktc_fifo_write") */
#line 294
/* #pragma cilnoremove("ktc_simpson") */
#line 295
/* #pragma cilnoremove("ktc_set_sched") */
#line 296
/* #pragma cilnoremove("ktc_gettime") */
#line 297
/* #pragma cilnoremove("list_dl") */
#line 298
/* #pragma cilnoremove("list_pr") */
#line 299
/* #pragma cilnoremove("populatelist") */
#line 300
/* #pragma cilnoremove("sched_getattr") */
#line 301
/* #pragma cilnoremove("log_trace_end_id") */
#line 302
/* #pragma cilnoremove("log_trace_abort_time") */
#line 303
/* #pragma cilnoremove("log_trace_release") */
#line 304
/* #pragma cilnoremove("log_trace_execution") */
#line 305
/* #pragma cilnoremove("log_trace_arrival") */
#line 306
/* #pragma cilnoremove("log_trace_init_tp") */
#line 307
/* #pragma cilnoremove("log_trace_init") */
#line 308
/* #pragma cilnoremove("clock_gettime") */
#line 309
/* #pragma cilnoremove("sae") */
#line 310
/* #pragma cilnoremove("fopen") */
#line 4 "log.h"
extern void log_trace_init(char const   *func , struct _IO_FILE *fp ) ;
#line 5
extern void log_trace_init_tp(struct _IO_FILE *fp , int tp , long *arrival_init , struct timespec itime ) ;
#line 6
extern void log_trace_arrival(FILE *fp , int tp , int interval , int res , long *last_arrival ) ;
#line 7
extern void log_trace_release(FILE *fp , long last_arrival , struct timespec itime , struct timespec *stime , int interval ) ;
#line 8
extern void log_trace_execution(FILE *fp , struct timespec stime ) ;
#line 9
extern void log_trace_end_id(FILE *fp , int id , struct timespec stime ) ;
#line 10
extern void log_trace_abort_time(FILE *fp , long last_arrival , struct timespec stime , int interval , int id ) ;
#line 12 "test1.c"
extern void mrad2deg(int k ) ;
#line 16 "test1.c"
FILE dfile  ;
#line 22
extern int ( /* missing proto */  sdelay)() ;
#line 18 "test1.c"
void * __attribute__((__task__)) tsk_foo(void) 
{ 
  int i ;

  {
#line 20
  i = 0;
#line 20
  while (i < 50) {
#line 21
    mrad2deg(50);
#line 22
    sdelay(30, 30, -3);
#line 20
    i ++;
  }
#line 24
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 31
extern int ( /* missing proto */  basicmath_small)() ;
#line 27 "test1.c"
void * __attribute__((__task__)) tsk_bar(void) 
{ 
  int i ;

  {
#line 30
  i = 0;
#line 30
  while (i < 50) {
#line 31
    basicmath_small();
#line 32
    sdelay(20, 20, -3);
#line 30
    i ++;
  }
#line 35
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 41
extern int ( /* missing proto */  rad2deg)() ;
#line 38 "test1.c"
void * __attribute__((__task__)) tsk_far(void) 
{ 
  int i ;

  {
#line 40
  i = 0;
#line 40
  while (i < 50) {
#line 41
    rad2deg(100);
#line 42
    sdelay(60, 60, -3);
#line 40
    i ++;
  }
#line 44
  return ((void */* __attribute__((__task__)) */)0);
}
}
#line 48 "test1.c"
int *dummyglobalvariable  ;
#line 48 "test1.c"
int populatelist(int num ) 
{ 


  {
#line 48
  if (num == 0) {
#line 48
    return (0);
  }
#line 48
  qsort(list_dl, num, sizeof(int ), & compare_qsort);
#line 48
  qsort(list_pr, num, sizeof(int ), & compare_qsort);
#line 48
  return (1);
}
}
#line 48 "test1.c"
void main(void) 
{ 
  unsigned long targ ;

  {
#line 49
  targ = 10;
#line 50
  tsk_foo();
#line 51
  tsk_bar();
#line 52
  tsk_far();
#line 53
  printf("main--end\n");
#line 54
  return;
}
}
